### ISSUE TITLE
Addressable value bug

### ISSUE THREAD

**Issue by nicolas-goyon** [EduardMalkhasyan/Serializable-Dictionary-Unity#3]
Hi there,
I've been stuck with an issue where the value of the dictionnary is AssetGUID and not a drop field, I have this issue with AddressablesReferences and AddressablesReferencesT<>.

![image](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/assets/38950115/826eec37-40f2-4053-bf19-ec2584d7661d)

Thanks in advance for the help.

**Comment by EduardMalkhasyan** [comment]
Hello @nicolas-goyon sorry for having trouble with my plugin. I found the solution but am not sure if you want to use it...

Here is the problem - as you can see  `AssetReference` class is Serializable class but it use ` [FormerlySerializedAs("m_assetGUID")]`
attribute because of being non MonoBehaviour inherited class  
![Screenshot_3](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/assets/78969017/50a4242f-e167-4560-8365-f82d4f3eedf7)

so the only solution I can provide you in this case, is parent your class with other class and it will not understand the first 
` [FormerlySerializedAs("m_assetGUID")]`
![image](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/assets/78969017/42f02c78-9c9a-438c-9db7-7349095f53be)

Solution here 
![image](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/assets/78969017/c4cafb89-f8e2-4732-88c1-eed4f06b6065)

**Comment by EduardMalkhasyan** [comment]
If its ok for @nicolas-goyon you I can close the Issue ?

**Comment by nicolas-goyon** [comment]
Yes its ok for me, thanks for the solution, i'll take this one it could work.

**Comment by EduardMalkhasyan** [comment]
Hello @nicolas-goyon new version has the fix - [V_2_01](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/releases)
and also it has serialize interface with mono feature

**Comment by nicolas-goyon** [comment]
> Hello @nicolas-goyon new version has the fix - [V_2_01](https://github.com/EduardMalkhasyan/Serializable-Dictionary-Unity/releases)
> and also it has serialize interface with mono feature

Ohh nice thanks !
